#!/bin/bash
# Test script for namespace fix verification
# Version: v1.1
# Date: 2025-11-30

set -e

echo "================================================"
echo "ML Platform Namespace Fix - Test Script"
echo "Backend v1.1 + Frontend v1.5"
echo "================================================"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "1. Checking Deployment Versions"
echo "--------------------------------"
echo -n "Backend version: "
kubectl get deployment ml-platform-backend -n kubeflow -o jsonpath='{.spec.template.spec.containers[0].image}'
echo ""

echo -n "Frontend version: "
kubectl get deployment ml-platform-frontend -n kubeflow -o jsonpath='{.spec.template.spec.containers[0].image}'
echo ""

echo ""
echo "2. Checking Pod Status"
echo "--------------------------------"
kubectl get pods -n kubeflow -l app=ml-platform,component=backend -o wide
kubectl get pods -n kubeflow -l app=ml-platform,component=frontend -o wide

echo ""
echo "3. Testing Backend Logs"
echo "--------------------------------"
echo "Recent backend logs (looking for namespace handling):"
kubectl logs -n kubeflow -l app=ml-platform,component=backend --tail=5 2>/dev/null | grep -E "User|namespace|Creating" || echo "No relevant logs yet"

echo ""
echo "================================================"
echo "Manual Testing Instructions"
echo "================================================"
echo ""
echo "1. Access Kubeflow UI:"
echo "   http://192.168.40.246:32269"
echo ""
echo "2. Login with credentials:"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
echo "3. Navigate to Training Jobs:"
echo "   Click 'Training Jobs' in left menu"
echo "   Or go to: http://192.168.40.246:32269/_/training-job/"
echo ""
echo "4. Open Browser DevTools (F12):"
echo "   - Go to Network tab"
echo "   - Filter by 'env-info'"
echo "   - Check the response shows: {namespace: 'admin', ...}"
echo ""
echo "5. Create a test job:"
echo "   - Click 'Create Training Job'"
echo "   - Fill in job details:"
echo "     * Job Name: test-namespace-fix-$(date +%s)"
echo "     * Algorithm: XGBoost"
echo "     * Upload a CSV file or configure object storage"
echo "     * Output path: storage://output/"
echo "   - Click 'Submit'"
echo ""
echo "6. Verify in Network tab:"
echo "   - Find POST request to /api/training-job/v1/jobs"
echo "   - Check payload contains: {\"namespace\": \"admin\", ...}"
echo ""
echo "7. Check backend logs:"
echo "   kubectl logs -n kubeflow -l app=ml-platform,component=backend --tail=20"
echo ""
echo "   Expected log:"
echo "   'User admin@dcn.com creating job 'test-...' in namespace 'admin''"
echo ""
echo "8. Verify RayJob created in admin namespace:"
echo "   kubectl get rayjobs -n admin"
echo ""
echo "   ✅ SUCCESS: Job appears in 'admin' namespace"
echo "   ❌ FAILURE: Job not found or error about namespace not found"
echo ""
echo "================================================"
echo "Troubleshooting"
echo "================================================"
echo ""
echo "If job creation fails:"
echo ""
echo "Check 1: Verify namespace exists"
echo "  kubectl get namespace admin"
echo ""
echo "Check 2: Check Ray operator is installed"
echo "  kubectl get pods -n ray-system"
echo ""
echo "Check 3: Check backend can access admin namespace"
echo "  kubectl auth can-i create rayjobs -n admin --as=system:serviceaccount:kubeflow:ml-platform-backend"
echo ""
echo "Check 4: View detailed backend logs"
echo "  kubectl logs -n kubeflow -l app=ml-platform,component=backend --tail=50"
echo ""
echo "Check 5: Verify frontend sent correct namespace"
echo "  # In browser console after submit"
echo "  # Look at Network tab → POST request payload"
echo ""

echo "================================================"
echo "Quick Verification Commands"
echo "================================================"
echo ""
echo "# Check if admin namespace exists:"
echo "kubectl get namespace admin"
echo ""
echo "# List all RayJobs in admin namespace:"
echo "kubectl get rayjobs -n admin"
echo ""
echo "# Watch backend logs in real-time:"
echo "kubectl logs -n kubeflow -l app=ml-platform,component=backend -f"
echo ""
echo "# Check Ray operator:"
echo "kubectl get pods -n ray-system"
echo ""
